package com.khalifapps.muslimgenz.presentation.theme

object HomeStrings {
    const val ISLAMIC_DATE = "15 Shawwal 1445"
    const val GREGORIAN_DATE = "May 24, 2024"
    const val GREETING_TITLE = "Assalamu'alaikum, Khalif"
    const val GREETING_SUBTITLE = "May your day be filled with barakah"
    const val PRAYER_NAME = "Asr"
    const val PRAYER_COUNTDOWN = " · in 2h 14m"
    const val PRAYER_NEXT = "Next: 3:45 PM"
    const val SECTION_REELS = "Inspiration Reels"
    const val SEE_ALL = "SEE ALL"
    const val REEL_MORNING_DHIKR = "Morning Dhikr"
    const val REEL_MORNING_VIEWS = "12.4k views"
    const val REEL_CALLIGRAPHY = "Art of Calligraphy"
    const val REEL_CALLIGRAPHY_VIEWS = "8.9k views"
    const val AYAH_HEADER = "AYAH OF THE DAY"
    const val AYAH_ARABIC = "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا"
    const val AYAH_TRANSLATION = "\"For indeed, with hardship [will be] ease.\""
    const val AYAH_SOURCE = "— Surah Ash-Sharh 94:5"
    const val MENU_QURAN = "Quran"
    const val MENU_HADITH = "Hadith"
    const val MENU_STORIES = "Stories"
    const val MENU_DAKWAH = "Dakwah"
    const val MENU_PRAYER = "Prayer"
    const val MENU_CALENDAR = "Calendar"
    const val MENU_QIBLA = "Qibla"
    const val MENU_ALL = "All"
    const val KAJIAN_HEADER = "Kajian Buat Kamu"
    const val KAJIAN_TITLE = "Kajian Ust. Khalid Basalamah\n(Kisah Sahabat Nabi Bagian 1)"
    const val KAJIAN_AUTHOR = "UST. KHALID BASALAMAH"
    const val DISCOVER_HEADER = "Discover Content"
    const val DISCOVER_SEE_ALL = "Lihat Semuanya"
    const val DISCOVER_ITEM1_TITLE = "Galau 😭"
    const val DISCOVER_ITEM1_SUBTITLE = "Dari galau jadi pahala\nyuk, dengerin kajian anti.."
    const val DISCOVER_ITEM2_TITLE = "Sabar ajah"
    const val DISCOVER_ITEM2_SUBTITLE = "Cungg siapa yang tiap\nhari nahan sabar.."
    const val DISCOVER_ITEM3_TITLE = "Berat ya"
    const val DISCOVER_ITEM3_SUBTITLE = "Kadang saat kita\nmencoba berubah sela.."
}
