package com.khalifapps.muslimgenz.presentation.navigation

object Routes {
    const val Splash = "splash"
    const val Welcome = "welcome"
    const val Login = "login"
    const val Register = "register"
    const val LoginEmail = "login_email"
    const val RegisterEmail = "register_email"
    const val LoginPhone = "login_phone"
    const val RegisterPhone = "register_phone"
    const val VerifyOtp = "verify_otp"
    const val Choice = "choice"
    const val ChoiceUstadz = "choice_ustadz"
    const val ChoiceTopic = "choice_topic"
    const val Result = "result"
    const val Home = "home"
    const val Reflection = "reflection"
    const val Playlist = "playlist"
    const val Share = "share"
    const val LoFi = "lofi"
    const val Prayer = "prayer"
    const val Search = "search"
    const val TrendingNowDetail = "trending_now_detail"
    const val AtmosphereDetail = "atmosphere_detail"
    const val Calendar = "calendar"
}